### ISSUE TITLE
Need Somehing New

### ISSUE THREAD

**Issue by BotolMehedi** [shellcxd3/AAAAAAAAAAAAA#2]
@shellmage 

If anyone removed any message from my messenger group chat The CHATBOT automatically resend the deleted message again.

Can you please make a BOT like this??

**Comment by shellmage** [comment]
yes, I can.

**Comment by BotolMehedi** [comment]
@shellmage So please make the bot 🙏🙏🙏🙏🙏 I really Need this 😭😭😭
